### ISSUE TITLE
Implementing clean shutdown (via Ctrl+C)

### ISSUE THREAD

**Issue by mafredri** [opennota/findimagedupes#8]
So, while I'm at it, curious if there would be interest in implementing clean shutdown, e.g. capturing SIGINT? I'm thinking this could avoid potential DB corruption and I've seen some pretty long error output coming from pHash or CImg 😄.

If yes, are `context`s OK or does `findimagedupes` want to support <Go1.8?

With regards to implementation, I'm thinking:

1. If pruning, abort after current
2. If walking, abort & close DB (pending hashes are discarded)
3. Close DB after successful walk and stop handling SIGINT
4. No special handling for "Find similar hashes" or "Print" (trust SIGINT propagation)

**Comment by opennota** [comment]
`context` is okay.

> With regards to implementation, I'm thinking:
>
>    If pruning, abort after current
>    If walking, abort & close DB (pending hashes are discarded)
>    Close DB after successful walk and stop handling SIGINT
>    No special handling for "Find similar hashes" or "Print" (trust SIGINT propagation)

LGTM.

**Comment by mafredri** [comment]
I've hit a bit of a snag, I've managed to get cancellation working but it's not working very well. The moment we've called out to `phash.ImageHashDCT` once we run into `morestack on g0` errors (tested by adding `phash.ImageHashDCT("random.jpg")` at the top of the program).

<details>
<summary>fatal: morestack on g0</summary>

```
...
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
fatal: morestack on g0
runtime: gp: gp=0xc420000180, goid=67462374, gp->atomicstatus=0
runtime:  g:  g=0xc42005c780, goid=0,  g->atomicstatus=0
fatal error: bad g->status in ready

runtime stack:
runtime.throw(0x42c72a6, 0x16)
	/usr/local/opt/go/libexec/src/runtime/panic.go:605 +0x95
runtime.ready(0xc420000180, 0x3, 0xc420049701)
	/usr/local/opt/go/libexec/src/runtime/proc.go:569 +0x2b2
runtime.goready.func1()
	/usr/local/opt/go/libexec/src/runtime/proc.go:288 +0x38
runtime.systemstack(0xc420021300)
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/local/opt/go/libexec/src/runtime/proc.go:1125

goroutine 15 [running]:
runtime.systemstack_switch()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:298 fp=0xc4200499d8 sp=0xc4200499d0 pc=0x40563a0
runtime.goready(0xc420000180, 0x3)
	/usr/local/opt/go/libexec/src/runtime/proc.go:287 +0x4b fp=0xc420049a08 sp=0xc4200499d8 pc=0x402d93b
runtime.recv(0xc420074300, 0xc4200a2ae0, 0xc420049e78, 0xc420049c70, 0x2)
	/usr/local/opt/go/libexec/src/runtime/chan.go:576 +0xb7 fp=0xc420049a40 sp=0xc420049a08 pc=0x40075c7
runtime.selectgo(0xc420049f20, 0xc420074300)
	/usr/local/opt/go/libexec/src/runtime/select.go:589 +0x83d fp=0xc420049cb8 sp=0xc420049a40 pc=0x403c64d
main.worker(0x43941a0, 0xc4200585c0, 0xc42007a4b0, 0xc420074300, 0xc4200742a0, 0xc420074540)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:70 +0x265 fp=0xc420049fb0 sp=0xc420049cb8 pc=0x410d5a5
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420049fb8 sp=0xc420049fb0 pc=0x4058f31
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:316 +0xa70

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 67462374 [idle]:

goroutine 10 [runnable]:
sync.runtime_SemacquireMutex(0xc42007a4bc, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42007a4b8)
	/usr/local/opt/go/libexec/src/sync/mutex.go:134 +0xee
sync.(*RWMutex).Lock(0xc42007a4b8)
	/usr/local/opt/go/libexec/src/sync/rwmutex.go:93 +0x2d
main.(*DB).Upsert(0xc42007a4b0, 0x43941a0, 0xc4200585c0, 0xc42021d560, 0x55, 0x0, 0xec78bc10b, 0x43a9580, 0xbec6883b61c7921b, 0x0, ...)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/db.go:90 +0x8a
main.worker(0x43941a0, 0xc4200585c0, 0xc42007a4b0, 0xc420074300, 0xc4200742a0, 0xc420074360)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:110 +0x6d3
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:316 +0xa70

goroutine 11 [semacquire]:
sync.runtime_SemacquireMutex(0xc42007a4bc, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42007a4b8)
	/usr/local/opt/go/libexec/src/sync/mutex.go:134 +0xee
sync.(*RWMutex).Lock(0xc42007a4b8)
	/usr/local/opt/go/libexec/src/sync/rwmutex.go:93 +0x2d
main.(*DB).Upsert(0xc42007a4b0, 0x43941a0, 0xc4200585c0, 0xc42021d680, 0x55, 0x0, 0xec78d0f44, 0x43a9580, 0x30858f1f2ee75a70, 0x0, ...)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/db.go:90 +0x8a
main.worker(0x43941a0, 0xc4200585c0, 0xc42007a4b0, 0xc420074300, 0xc4200742a0, 0xc4200743c0)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:110 +0x6d3
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:316 +0xa70

goroutine 12 [semacquire]:
sync.runtime_SemacquireMutex(0xc42007a4bc, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42007a4b8)
	/usr/local/opt/go/libexec/src/sync/mutex.go:134 +0xee
sync.(*RWMutex).Lock(0xc42007a4b8)
	/usr/local/opt/go/libexec/src/sync/rwmutex.go:93 +0x2d
main.(*DB).Upsert(0xc42007a4b0, 0x43941a0, 0xc4200585c0, 0xc420201d40, 0x55, 0x0, 0xec78a9dbb, 0x43a9580, 0x1bd6d767301aec6, 0x0, ...)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/db.go:90 +0x8a
main.worker(0x43941a0, 0xc4200585c0, 0xc42007a4b0, 0xc420074300, 0xc4200742a0, 0xc420074420)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:110 +0x6d3
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:316 +0xa70

goroutine 13 [syscall, locked to thread]:
github.com/opennota/phash._C2func_ph_dct_imagehash_wrapper(0x5104f40, 0x0, 0x0, 0x0)
	github.com/opennota/phash/_obj/_cgo_gotypes.go:47 +0x60
github.com/opennota/phash.ImageHashDCT(0xc420219f50, 0x2e, 0x0, 0x0, 0x0)
	/Users/mafredri/Golang/src/github.com/opennota/phash/phash.go:40 +0x88
main.worker(0x43941a0, 0xc4200585c0, 0xc42007a4b0, 0xc420074300, 0xc4200742a0, 0xc420074480)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:98 +0x35b
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:316 +0xa70

goroutine 14 [syscall, locked to thread]:
github.com/opennota/phash._C2func_ph_dct_imagehash_wrapper(0x50005c0, 0x0, 0x0, 0x0)
	github.com/opennota/phash/_obj/_cgo_gotypes.go:47 +0x60
github.com/opennota/phash.ImageHashDCT(0xc420219ef0, 0x2e, 0x0, 0x0, 0x0)
	/Users/mafredri/Golang/src/github.com/opennota/phash/phash.go:40 +0x88
main.worker(0x43941a0, 0xc4200585c0, 0xc42007a4b0, 0xc420074300, 0xc4200742a0, 0xc4200744e0)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:98 +0x35b
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:316 +0xa70

goroutine 16 [syscall, locked to thread]:
github.com/opennota/phash._C2func_ph_dct_imagehash_wrapper(0x5102230, 0x0, 0x0, 0x0)
	github.com/opennota/phash/_obj/_cgo_gotypes.go:47 +0x60
github.com/opennota/phash.ImageHashDCT(0xc4202266c0, 0x2e, 0x0, 0x0, 0x0)
	/Users/mafredri/Golang/src/github.com/opennota/phash/phash.go:40 +0x88
main.worker(0x43941a0, 0xc4200585c0, 0xc42007a4b0, 0xc420074300, 0xc4200742a0, 0xc4200745a0)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:98 +0x35b
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:316 +0xa70

goroutine 18 [runnable]:
main.resultWorker(0xc42007a4e0, 0xc4200742a0, 0xc420074600)
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:43 +0x68
created by main.main
	/Users/mafredri/Golang/src/github.com/opennota/findimagedupes/main.go:322 +0xb29
```

</details>

From [os/signal](https://golang.org/pkg/os/signal/):

> If the non-Go code installs any signal handlers, it must use the SA_ONSTACK flag with sigaction. Failing to do so is likely to cause the program to crash if the signal is received. Go programs routinely run with a limited stack, and therefore set up an alternate signal stack. Also, the Go standard library expects that any signal handlers will use the SA_RESTART flag. Failing to do so may cause some library calls to return "interrupted system call" errors.

Do you know if pHash, or CImg registers any signal handlers? I tried to take a quick look but `cgo` and C++ isn't exactly my forté.

**Comment by opennota** [comment]
I don't get any panics (linux/amd64), but sometimes (more often than not) Ctrl+C doesn't work. I use this test program:

``` go
package main

import (
	"fmt"
	"os"
	"os/signal"

	"github.com/opennota/phash"
)

func main() {
	c := make(chan os.Signal)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		os.Exit(0)
	}()
	for i := 0; i < 4; i++ {
		go func() {
			for {
				phash.ImageHashDCT("random.jpg")
			}
		}()
	}
	select {}
}
```

**Comment by mafredri** [comment]
I also didn't get panics using the above code, but I believe that is due to `os.Exit(0)`. If I modify it slightly (add a print), I do see panic traces as well:

```go
	go func() {
		<-c
		fmt.Println("interrupt")
		os.Exit(0)
	}()
```

With or without print, I still see the `fatal: morestack on g0` though.

**Comment by opennota** [comment]
No "morestack on g0" messages for me in either case.

The pthread library does indeed call `rt_sigaction` without the `SA_ONSTACK` flag, but that doesn't seem to matter. Does the following program prints anything besides "interrupt" on your machine?

``` go
package main

import (
	"fmt"
	"os"
	"os/signal"
)

//#cgo CXXFLAGS: -lpthread
//
// long long pretendToWork() {
//   long long i, n = 0;
//   for (i=0; i<1000000000L; i++)
//     n*=i;
//   return n;
// }
import "C"

var tmp C.longlong

func main() {
	c := make(chan os.Signal)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		fmt.Println("interrupt")
		os.Exit(0)
	}()
	for i := 0; i < 4; i++ {
		go func() {
			for {
				tmp = C.pretendToWork()
			}
		}()
	}
	select {}
}
```

**Comment by opennota** [comment]
I've files an issue about missing signals: https://github.com/golang/go/issues/21905

**Comment by mafredri** [comment]
The above program only prints `interrupt`, as I would expect.

And thanks for opening up the issue and creating a repro!

**Comment by opennota** [comment]
Well, it seems that it can be solved...

**Comment by mafredri** [comment]
Yeah, that's unfortunate :-(. Do you think it would be feasible to patch `CImg` to call out to Go code instead of calling `std::stystem` (right now I'm assuming that's the only problem)?

**Comment by opennota** [comment]
It turns out CImg natively supports jpeg, png and tiff files (via libjpeg, libpng and libtiff). That leaves GIFs, which are currently loaded only with the help of external tools.

Also I've found and fixed a bug in pHash C++ library which caused incorrect fingerprinting of RGBA files.

I'll update the phash package soon.

**Comment by opennota** [comment]
phash is updated. Is it better now?

**Comment by mafredri** [comment]
Nice, the updated `phash` is a big improvement! As long as no GIF has been processed, interrupts are handled properly, but as soon as even a single GIF has been processed I see the same (`morestack`) problem as before (this *effect* lasts for the duration of the program).

Btw,  I had to add these lines on macOS to compile it though (`phash.go`):

```go
#cgo CXXFLAGS: -I/usr/local/opt/libjpeg/include -I/usr/local/opt/libpng/include -I/usr/local/opt/libtiff/include
#cgo LDFLAGS: -L/usr/local/opt/libjpeg/lib -L/usr/local/opt/libpng/lib -L/usr/local/opt/libtiff/lib
```

**Comment by opennota** [comment]
Does adding a file `phash_darwin.go`:

```
package phash

// #cgo CXXFLAGS: -O2 -Ic++/CImg -Ic++/pHash
// #cgo LDFLAGS: -ljpeg -lpngx -ltiff
import "C"
```

with the necessary flags help?

**Comment by opennota** [comment]
How come libjpeg and others are under /usr/local? Are they installed manually?

**Comment by opennota** [comment]
You can also try replacing `#cgo LDFLAGS ...` in `phash.go` with `#cgo pkg-config: libjpeg libpng libtiff-4` (which incidentally works on linux).

**Comment by mafredri** [comment]
I added the following `phash_darwin.go` with no other changes:

```go
// +build darwin

package phash

// #cgo CXXFLAGS: -I/usr/local/opt/libjpeg/include -I/usr/local/opt/libpng/include -I/usr/local/opt/libtiff/include
// #cgo LDFLAGS: -L/usr/local/opt/libjpeg/lib -L/usr/local/opt/libpng/lib -L/usr/local/opt/libtiff/lib
import "C"
```

It works 👍. The reason the flags are needed is that these are from Homebrew (`brew install libjpeg libpng libtiff`). They don't seem to be natively available on macOS. The `pkg-config` alternative did not work due `libjpeg` missing a pkgconfig.

**Comment by opennota** [comment]
Good. You don't need both _darwin suffix and `+build darwin` tag, though.

**Comment by mafredri** [comment]
Ah, you're right, forgot about that :-).

**Comment by opennota** [comment]
I've updated phash.

**Comment by opennota** [comment]
As for GIFs (and other rare formats), try adding `-Dcimg_no_system_calls` to CXXFLAGS in phash.go. CImg will use `popen` instead of `system`.

**Comment by mafredri** [comment]
When I enable `-Dcimg_no_system_calls` I keep seeing this for all GIFs:

```
WARNING: mygif1.gif: no such file or directory
```

However, it does allow interrupts to work as expected, even after attempting to process GIFs.

**Comment by opennota** [comment]
> WARNING: : cannot stat `' (No such file or directory)

Fixed in https://github.com/opennota/findimagedupes/commit/72ef7ae7629895766bfda89793e7a87f12f324c3

**Comment by mafredri** [comment]
Thanks, sorry I missed that. I think 72ef7ae minimizes the chance of it happening, but does not fix it entirely. My hunch is that If an interrupt is received just after a message is received on `in` we might still see `WARNING: : cannot stat `' (No such file or directory)` but I have not confirmed this theory.

**Comment by opennota** [comment]
How so? `m.path` won't be empty in that case and so you can't see `cannot stat `'` (empty file name).

**Comment by mafredri** [comment]
Oh yeah 🤦‍♂️, never mind. I imagined the problem was elsewhere.
